### ISSUE TITLE
Not Restarting my IOS APP

### ISSUE THREAD

**Issue by MbohBless** [Zhalkhas/phoenix_native#1]
i get this no channel error when i install this dependency so please i will really be greatful that this is arranged
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method restart on channel phoenix_native)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      PhoenixNative.restartApp (package:phoenix_native/phoenix_native.dart:10:12)
<asynchronous suspension>

**Comment by tyypgzl** [comment]
Same bug @MbohBless

**Comment by MbohBless** [comment]
## Proposed Solution using state management
@tyypgzl i think the best thing to do with what is causing the problem is to use a state management took which can be refreshed when you use a trigger from one screen or another 
i would personally recommend [Riverpod](https://riverpod.dev/) or if you want to be an explorer  [Bloc](https://bloclibrary.dev/#/).
In my case, I made use of the autodospose feature of riverpod which was a game changer for me
